apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 099881965479.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 099881965479.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: c772dee8
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
